#!/bin/bash

# Check if script is running on Docker
if grep -q docker /proc/1/cgroup; then
    # Configure localhost to resolve to 127.0.0.2
    sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
    
    # Configure facebook.com to resolve to 8.8.8.8
    sudo sed -i 's/\(facebook.com\).*/\1 8.8.8.8/g' /etc/hosts
    
    echo "Configuration completed."
else
    echo "This script is intended to run on Docker. Exiting."
    exit 1
fi