#!/bin/bash

# Retrieve active IPv4 IPs using the ifconfig command
active_ips=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*')

# Loop through each active IP and display it
for ip in $active_ips; do
    echo "$ip"
done
